# Generated by Django 4.1.4 on 2023-04-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='address',
        ),
    ]
